import { Button, LightMode, Spacer } from '@chakra-ui/react'
import Head from 'next/head'
import { useState, useEffect } from 'react';
import { M_PLUS_1p } from 'next/font/google'
import styles from '@/styles/pages/Home.module.css'
import Header from '@/components/utils/header'

const m_plus_1p_700_font = M_PLUS_1p({
  weight: "700",
  subsets: ["latin"],
});

export default function Home() {

  const [isTop, setIsTop] = useState(false);

  const toggleIsTop = () => {
    window.scrollY > (window.innerHeight +10) ? setIsTop(true) : setIsTop(false);
    console.log("isTop: "+isTop+", scroll: "+window.scrollY+", screenY: "+window.innerHeight)
  };

  useEffect(() => {
    window.addEventListener("scroll", toggleIsTop);
    return () => window.removeEventListener("scroll", toggleIsTop);
  }, []);

  return (
    <>
      <Head>
        <title>ホーム - 今日鯖</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="rgb(39 39 42)" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      
      <div className={ isTop ? styles.hiddenTop : styles.top }>
        <img src="/img/lobby.png" alt="" />
        <div className={styles.title}>
          <p><span className='text-kyousaba'>今日鯖</span>へようこそ！</p>
          <div className={styles.subtitle}>
            普段のサバイバルでは味わえない<br/>
            「今日鯖ならでは」の機能を体験してみよう！<br/>

            <div className={styles.buttons}>
              <LightMode>
              <Button colorScheme='green' size={"lg"} ><span className={m_plus_1p_700_font.className}>参加方法を見る</span></Button>
              <a href='https://discord.kyousaba.net/'><Button colorScheme='messenger' size={"lg"}><span className={m_plus_1p_700_font.className}>Discordに参加する</span></Button></a>
              </LightMode>
            </div>
          </div>
        </div>
      </div>

      <Spacer height={"100vh"}/>

      <div className='content'>
        <div className={styles.content}>
          <Button colorScheme='blue'>Button</Button>
          <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
        </div>
      </div>
    </>
  )
}
